Repository AY2223S1-CS2103T-T12-3/tp, pull requests merged in 2022-10, with the labels that each got.

#60 Different colours for different tags
  src/main/java/hobbylist/ui/ActivityCard.java
Labels: enhancement

#97 Rename FindTag to FilterTag
  src/main/java/hobbylist/logic/commands/FilterTagCommand.java
  src/main/java/hobbylist/logic/parser/FilterTagCommandParser.java
  src/main/java/hobbylist/logic/parser/HobbyListParser.java
  src/test/java/hobbylist/logic/commands/FilterTagCommandTest.java
  src/test/java/hobbylist/logic/parser/FilterTagCommandParserTest.java
Labels: enhancement

#123 Update UG
  docs/UserGuide.md
Labels: documentation

#124 Fix minor errors and update GUI
  docs/UserGuide.md
  docs/images/default_gui.jpg
  docs/images/default_gui.png
Labels: documentation

#125 Update new UI in Readme
  README.md
Labels: documentation

#121 Add review to selectActivityPanel and fix error when selecting different task
  src/main/java/hobbylist/ui/ActivityCard.java
  src/main/java/hobbylist/ui/SelectedActivityPanel.java
  src/main/resources/view/SelectedActivityPanel.fxml
Labels: bug, enhancement

#131 Update UG and Index.md
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#143 Update UI
  src/main/resources/view/SelectedActivityPanel.fxml
Labels: bug

#191 Fix errors and add suggestions based on PE-D
  docs/UserGuide.md
  docs/images/default_gui.png
Labels: documentation

#193 Try to generate TOC in UG
  docs/UserGuide.md
Labels: documentation

#194 Update UG v1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation
